package view;

import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JEditorPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.event.HyperlinkEvent;

public class AboutDialog {

	private JDialog dialog;
	private MainWindow mainWindow;

	public AboutDialog(MainWindow mainWindow) {
		this.mainWindow = mainWindow;
		SwingUtilities.invokeLater(this::build);
	}

	private void build() {
		dialog = new JDialog(mainWindow);
		dialog.setTitle("About GizmoBall");
		dialog.setResizable(false);
		dialog.setModal(true);
		String text = "<center><h3>GizmoBall</h3>" + "<p>&copy; Paul Bryden, R. David Dunphy, Michael Ewart,"
				+ "<br />Matthew Gaffney, Conor Waugh</p>"
				+ "<p>Icons generated by <a href=\"http://icons8.com\">icons8.com</a></p></center>";
		JEditorPane textPane = new JEditorPane();

		textPane.setEditorKit(JEditorPane.createEditorKitForContentType("text/html"));
		textPane.setText(text);
		textPane.setBackground(new Color(0, 0, 0, 0));
		textPane.setEditable(false);
		textPane.addHyperlinkListener(e -> {
            if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
                if (Desktop.isDesktopSupported()) {
                    try {
                        Desktop.getDesktop().browse(e.getURL().toURI());
                    } catch (IOException | URISyntaxException ignored) {}
                }
            }
        });
		JButton button = new JButton("Okay");
		button.addActionListener(e -> dialog.dispose());
		button.setAlignmentX(Component.CENTER_ALIGNMENT);
		JPanel panel = new JPanel();
		panel.setLayout(new BoxLayout(panel, BoxLayout.PAGE_AXIS));
		panel.add(textPane);
		panel.add(Box.createVerticalStrut(5));
		panel.add(button);
		panel.setBorder(BorderFactory.createEmptyBorder(10, 15, 15, 15));
		dialog.setContentPane(panel);
		dialog.pack();
		dialog.setLocationRelativeTo(mainWindow);
		dialog.setVisible(true);
	}

}
