package view;

import java.awt.Color;
import java.awt.Component;

import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public class AboutDialog {

	private JDialog dialog;
	private MainWindow mainWindow;

	public AboutDialog(MainWindow mainWindow) {
		this.mainWindow = mainWindow;
		SwingUtilities.invokeLater(this::build);
	}

	private void build() {
		dialog = new JDialog(mainWindow);
		dialog.setTitle("About GizmoBall");
		dialog.setResizable(true);
		dialog.setModal(true);
		String text = "<html><center><h3>GizmoBall</h3>" + "<p>&copy; Paul Bryden, R. David Dunphy, Michael Ewart,"
				+ "<br />Matthew Gaffney, Conor Waugh</p>"
				+ "<p>Icons generated by <a href=\"http://icons8.com\">icons8.com</a></p></center><html>";
		JLabel textLabel = new JLabel();
		textLabel.setText(text);
		textLabel.setBackground(new Color(0, 0, 0, 0));
		JPanel panel = new JPanel();
		panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
		panel.add(textLabel);
		panel.setAlignmentX(Component.CENTER_ALIGNMENT);
		panel.setBorder(BorderFactory.createEmptyBorder(10, 15, 15, 15));
		dialog.setContentPane(panel);
		dialog.pack();
		dialog.setLocationRelativeTo(mainWindow);
		dialog.setVisible(true);
	}

}
